import { db } from "../db";
import { companies } from "@shared/schema";

const sampleCompanies = [
  {
    name: "Sierra Space",
    description: "Commercial space company developing the Dream Chaser spaceplane and LIFE habitat for low Earth orbit.",
    sector: "Space",
    city: "Louisville",
    website: "https://sierraspace.com",
    fundingStage: "Series F",
    fundingAmount: "$290M",
    employeeCount: "1000+",
    founded: 2021,
  },
  {
    name: "Atom Computing",
    description: "Building scalable quantum computers using nuclear spin qubits in arrays of optically-trapped neutral atoms.",
    sector: "Quantum",
    city: "Boulder",
    website: "https://atom-computing.com",
    fundingStage: "Series B",
    fundingAmount: "$60M",
    employeeCount: "50-100",
    founded: 2018,
  },
  {
    name: "Crusoe Energy",
    description: "Digital flare mitigation converting wasted natural gas into compute power for AI and Bitcoin mining.",
    sector: "Energy",
    city: "Denver",
    website: "https://crusoe.ai",
    fundingStage: "Series C",
    fundingAmount: "$350M",
    employeeCount: "200-500",
    founded: 2018,
  },
  {
    name: "Inscripta",
    description: "Synthetic biology platform providing digital genome engineering solutions for biotech research.",
    sector: "Biotech",
    city: "Boulder",
    website: "https://inscripta.com",
    fundingStage: "Series E",
    fundingAmount: "$150M",
    employeeCount: "200-500",
    founded: 2015,
  },
  {
    name: "Palantir Technologies",
    description: "Data analytics company with major operations in Denver focused on defense and commercial sectors.",
    sector: "AI",
    city: "Denver",
    website: "https://palantir.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "1000+",
    founded: 2003,
  },
  {
    name: "BAE Space & Mission Systems",
    description: "Space systems company providing spacecraft, instruments, and sensors for government and commercial customers. Formerly Ball Aerospace, acquired by BAE Systems in 2023.",
    sector: "Space",
    city: "Boulder",
    website: "https://baesystems.com/space",
    fundingStage: "Subsidiary",
    fundingAmount: "N/A",
    employeeCount: "1000+",
    founded: 1956,
  },
  {
    name: "Solid Power",
    description: "Developer of solid-state battery technology for electric vehicles with partnerships with BMW and Ford.",
    sector: "Energy",
    city: "Louisville",
    website: "https://solidpowerbattery.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "200-500",
    founded: 2012,
  },
  {
    name: "Biodesix",
    description: "Diagnostic company developing blood-based tests for lung cancer and other diseases.",
    sector: "Biotech",
    city: "Boulder",
    website: "https://biodesix.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "200-500",
    founded: 2006,
  },
  {
    name: "ColdQuanta (Infleqtion)",
    description: "Quantum computing company using cold atom technology for quantum sensors and computing.",
    sector: "Quantum",
    city: "Boulder",
    website: "https://infleqtion.com",
    fundingStage: "Series B",
    fundingAmount: "$110M",
    employeeCount: "100-200",
    founded: 2007,
  },
  {
    name: "Boom Supersonic",
    description: "Developing Overture, the world's fastest commercial aircraft for sustainable supersonic travel.",
    sector: "Space",
    city: "Denver",
    website: "https://boomsupersonic.com",
    fundingStage: "Series C",
    fundingAmount: "$270M",
    employeeCount: "200-500",
    founded: 2014,
  },
  {
    name: "Anduril Industries",
    description: "Defense technology company with Colorado operations focused on autonomous systems and AI.",
    sector: "AI",
    city: "Colorado Springs",
    website: "https://anduril.com",
    fundingStage: "Series E",
    fundingAmount: "$1.5B",
    employeeCount: "1000+",
    founded: 2017,
  },
  {
    name: "Lockheed Martin Space",
    description: "Major aerospace and defense contractor with significant space operations in Colorado.",
    sector: "Space",
    city: "Littleton",
    website: "https://lockheedmartin.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "1000+",
    founded: 1995,
  },
  {
    name: "Velo3D",
    description: "Additive manufacturing company specializing in 3D printing for aerospace and energy applications.",
    sector: "Space",
    city: "Denver",
    website: "https://velo3d.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "200-500",
    founded: 2014,
  },
  {
    name: "Array Labs",
    description: "Building synthetic aperture radar (SAR) satellite constellation for Earth observation.",
    sector: "Space",
    city: "Boulder",
    website: "https://arraylabs.space",
    fundingStage: "Seed",
    fundingAmount: "$15M",
    employeeCount: "10-50",
    founded: 2022,
  },
  {
    name: "Uplight",
    description: "Energy software platform helping utilities and their customers transition to clean energy.",
    sector: "Energy",
    city: "Boulder",
    website: "https://uplight.com",
    fundingStage: "Series C",
    fundingAmount: "$150M",
    employeeCount: "500-1000",
    founded: 2019,
  },
  {
    name: "Viome",
    description: "Biotech company using AI and metatranscriptomics to analyze the gut microbiome for health insights.",
    sector: "Biotech",
    city: "Denver",
    website: "https://viome.com",
    fundingStage: "Series C",
    fundingAmount: "$75M",
    employeeCount: "100-200",
    founded: 2016,
  },
  {
    name: "Trimble",
    description: "Technology company providing GPS, laser, and optical positioning products for construction and agriculture.",
    sector: "AI",
    city: "Westminster",
    website: "https://trimble.com",
    fundingStage: "Public",
    fundingAmount: "N/A",
    employeeCount: "1000+",
    founded: 1978,
  },
  {
    name: "Maxar Technologies",
    description: "Space technology company providing Earth intelligence and space infrastructure solutions.",
    sector: "Space",
    city: "Westminster",
    website: "https://maxar.com",
    fundingStage: "Acquired",
    fundingAmount: "N/A",
    employeeCount: "1000+",
    founded: 2017,
  },
];

export async function seedCompanies() {
  console.log("Seeding companies...");
  
  for (const company of sampleCompanies) {
    try {
      await db.insert(companies).values(company).onConflictDoNothing();
      console.log(`Added: ${company.name}`);
    } catch (error) {
      console.log(`Skipped (may already exist): ${company.name}`);
    }
  }
  
  console.log("Seeding complete!");
}

seedCompanies().then(() => process.exit(0)).catch(console.error);
